### ISSUE TITLE
`upload_to` non configurable

### ISSUE THREAD

**Issue by SebCorbin** [uclouvain/osis-document#12]
Les fichiers sont actuellement tous enregistrés dans le même dossier et pour cause :
- lors de l'enregistrement, l'endpoint de `RequestUploadView` n'a aucune idée d'où provient le fichier
- idem pour l'endpoint de `ConfirmUploadView`

TODO

- [ ] Reprendre l'attribut `upload_to` de django.FileField et l'ajouter sur osis_document.FileField
- [ ] S'assurer qu'à l'upload (RequestUpload) le nom original (celui du PC de l'user) est sotcké dans les métadonnées
- [ ] Lors du `confirm_upload` et du `confirm_remote_upload`, prendre en paramètre cet `upload_to` pour déplacer le fichier au bon endroit (en utilisant le storage django)
- [ ] Vérifier que c'est toujours le `name` depuis les métadonnées qui est utilisé à l'affichage
- [ ] Empêcher la modification de l'extension (l'afficher à côté dans le widget ?) et vérifier qu'on ne mettre des caractères indésirable (`/[]`... rester sur du `r'/[0-9][a-z]_-/i')

**Comment by albrugnetti** [comment]
@SebCorbin Pour la configuration de **upload_to**, vue que RequestUploadView est une requête Server-to-Serveur, est-ce qu'on ne peut pas ajouter une donnée (dans meta) avec le chemin d'accès ?

**Comment by SebCorbin** [comment]
Après étude, ce paramètre devrait être renseigné dans le code (car certaines requêtes ne sont pas server-to-server) qui persiste (confirme) l'upload. On aurait à ce momoent plus de contexte, et il suffirait de déplacer le fichier.
